# Generated by Django 2.2 on 2020-12-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numéro')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=20, verbose_name='Prénom')),
                ('nom_personne_en_charge', models.CharField(max_length=20, verbose_name='Personne en charge de la commande')),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('nom', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nom')),
                ('nombre_client', models.IntegerField(blank=True, null=True, verbose_name='Nombre du client dans la commune')),
            ],
            options={
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(verbose_name="Date de l'intervention")),
                ('remarque', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarques du technicien')),
            ],
            options={
                'db_table': 'intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numéro')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=20, verbose_name='Prénom')),
                ('nombre_voiture_reparees', models.IntegerField(blank=True, null=True, verbose_name='Nombre des voitures réparées')),
            ],
            options={
                'db_table': 'technicien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeReparition',
            fields=[
                ('type', models.IntegerField(primary_key=True, serialize=False, verbose_name='Type')),
                ('details', models.CharField(max_length=200, verbose_name='Details')),
            ],
            options={
                'db_table': 'type_reparition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('marque', models.CharField(max_length=20, verbose_name='Marque')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('date_fabrication', models.DateField(verbose_name='Date de fabrication')),
                ('kilometrage', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
            ],
            options={
                'db_table': 'voiture',
                'managed': False,
            },
        ),
    ]
