# Generated by Django 2.2 on 2020-11-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('numtel', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=50)),
                ('prenom_employe', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('estActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='modele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
                ('detail_service', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='type_voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_voiture', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('date_fabrication', models.DateField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
                ('id_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.modele')),
            ],
        ),
        migrations.CreateModel(
            name='visite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visite_date', models.DateField()),
                ('matricule', models.CharField(max_length=10)),
                ('visite_prix', models.CharField(max_length=10)),
                ('estPayee', models.BooleanField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.service')),
                ('id_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.voiture')),
            ],
        ),
        migrations.AddField(
            model_name='modele',
            name='id_type_voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.type_voiture'),
        ),
        migrations.CreateModel(
            name='horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de', models.CharField(max_length=50)),
                ('temps_a', models.CharField(max_length=50)),
                ('date_horaire', models.DateField()),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employe')),
                ('id_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.poste')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='id_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.poste'),
        ),
    ]
