# Generated by Django 2.2 on 2020-11-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visite',
            name='estPayee',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numtel',
            field=models.CharField(max_length=50, verbose_name='Numéro du téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom_client',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_debut',
            field=models.DateField(verbose_name='Date du début du travail'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin du travail'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='estActive',
            field=models.BooleanField(verbose_name='Actuellement employé'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom_employe',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom_employe',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='date_horaire',
            field=models.DateField(verbose_name='Date du service'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='temps_a',
            field=models.CharField(max_length=50, verbose_name='Fin du service'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='temps_de',
            field=models.CharField(max_length=50, verbose_name='Début du service'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='nom_modele',
            field=models.CharField(max_length=50, verbose_name='Nom du modèle'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='nom_poste',
            field=models.CharField(max_length=50, verbose_name='Nom du poste'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_service',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=50, verbose_name='Nom du service'),
        ),
        migrations.AlterField(
            model_name='type_voiture',
            name='nom_type_voiture',
            field=models.CharField(max_length=50, verbose_name='Type de voiture'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='matricule',
            field=models.CharField(max_length=10, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='visite_date',
            field=models.DateField(verbose_name='Date de visite'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='visite_prix',
            field=models.CharField(max_length=10, verbose_name='Prix à payer'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='date_fabrication',
            field=models.DateField(verbose_name='Date de fabrication'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='matricule',
            field=models.CharField(max_length=10, verbose_name='Matricule'),
        ),
    ]
