# Generated by Django 2.2 on 2020-11-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201130_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.poste', verbose_name="Poste du l'employé"),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employe', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='id_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.poste', verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='id_type_voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.type_voiture', verbose_name='Type de voiture'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='id_voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.voiture', verbose_name='Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id_modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.modele', verbose_name='Modèle de la voiture'),
        ),
    ]
